define({
    _widgetLabel: "Meten",
    selectDrawMode: "Selecteer meetinstrument",
    clear: "Doorzichtig",
    point: "Punt",
    line: "Lijn",
    polyline: "Polylijn",
    extent: "Envelope",
    polygon: "Polygoon",
    text: "Tekst",
    style: "Stijl",
    alpha: "Transparantie",
    width: "Breedte",
    size: "Grootte",
    color: "Kleur",
    markerColor: "Markeer Kleur",
    outlineColor: "Overzicht kleur",
    lineColor: "Lijnkleur",
    fillColor: "Opvulkleur",
    showMeasurements: "Metingen weergeven",
    showTotals: "Metingstotalen weergeven",
	showPolylineTotal: "Interactieve polylijn totaal weergeven",
    showBearing: "Toon peiling",
    areaUnits: "Oppervlaktemaat",
    distanceUnits: "Lengtemaat",
    kilometers: "Kilometers",
    miles: "Mijlen",
    nauticalMiles: "Zeemijlen",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    squareKilometers: "Vierkante kilometer",
    squareMiles: "Vierkante mijl",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Vierkante meters",
    squareFeet: "Square feet",
    squareYards: "Square yards"
  });
