define({
  root: ({
    _widgetLabel: "Measure",
    selectDrawMode: "Select measure tool",
    clear: "Clear",
    point: "Point",
    line: "Line",
    polyline: "Polyline",
    extent: "Envelope",
    polygon: "Polygon",
    text: "Text",
    style: "Style",
    alpha: "Transparency",
    width: "Width",
    size: "Size",
    color: "Color",
    markerColor: "Marker Color",
    outlineColor: "Outline Color",
    lineColor: "Line Color",
    fillColor: "Fill Color",
    showMeasurements: "Show Measurements",
    showTotals: "Show Measurement Totals",
	showPolylineTotal: "Show Interactive Polyline Total",
    showBearing: "Show Bearing",
    areaUnits: "Area Units",
    distanceUnits: "Distance Units",
    kilometers: "Kilometers",
    miles: "Miles",
    nauticalMiles: "Nautical Miles",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    squareKilometers: "Square kilometers",
    squareMiles: "Square miles",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Square meters",
    squareFeet: "Square feet",
    squareYards: "Square yards"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": ({
    _widgetLabel: "Meten",
    selectDrawMode: "Selecteer meetinstrument",
    clear: "Doorzichtig",
    point: "Punt",
    line: "Lijn",
    polyline: "Polylijn",
    extent: "Envelope",
    polygon: "Polygoon",
    text: "Tekst",
    style: "Stijl",
    alpha: "Transparantie",
    width: "Breedte",
    size: "Grootte",
    color: "Kleur",
    markerColor: "Markeer Kleur",
    outlineColor: "Overzicht kleur",
    lineColor: "Lijnkleur",
    fillColor: "Opvulkleur",
    showMeasurements: "Metingen weergeven",
    showTotals: "Metingstotalen weergeven",
	showPolylineTotal: "Interactieve polylijn totaal weergeven",
    showBearing: "Toon peiling",
    areaUnits: "Oppervlaktemaat",
    distanceUnits: "Lengtemaat",
    kilometers: "Kilometers",
    miles: "Mijlen",
    nauticalMiles: "Zeemijlen",
    meters: "Meters",
    feet: "Feet",
    yards: "Yards",
    squareKilometers: "Vierkante kilometer",
    squareMiles: "Vierkante mijl",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Vierkante meters",
    squareFeet: "Square feet",
    squareYards: "Square yards"
  }),
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});